<?xml version="1.0" encoding="utf-8"?><Database Name="WebBanHangOnline" Class="MydataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-OMC8D9M\SQLEXPRESS;Initial Catalog=WebBanHangOnline;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="WebBanHangOnlineConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tb_category" Member="tb_categories">
    <Type Name="tb_category">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="tb_category_tb_product" Member="tb_products" ThisKey="Id" OtherKey="Category_Id" Type="tb_product" />
    </Type>
  </Table>
  <Table Name="dbo.tb_guest" Member="tb_guests">
    <Type Name="tb_guest">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tb_order" Member="tb_orders">
    <Type Name="tb_order">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="GuestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalPrice" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="tb_order_tb_orderDetail" Member="tb_orderDetails" ThisKey="Id" OtherKey="OrderId" Type="tb_orderDetail" />
    </Type>
  </Table>
  <Table Name="dbo.tb_orderDetail" Member="tb_orderDetails">
    <Type Name="tb_orderDetail">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tb_order_tb_orderDetail" Member="tb_order" ThisKey="OrderId" OtherKey="Id" Type="tb_order" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="tb_product_tb_orderDetail" Member="tb_product" ThisKey="ProductID" OtherKey="Id" Type="tb_product" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_product" Member="tb_products">
    <Type Name="tb_product">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductCode" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="QuantityInSock" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShortDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DetailDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Category_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tb_product_tb_orderDetail" Member="tb_orderDetails" ThisKey="Id" OtherKey="ProductID" Type="tb_orderDetail" />
      <Association Name="tb_product_tb_productImage" Member="tb_productImages" ThisKey="Id" OtherKey="Product_Id" Type="tb_productImage" />
      <Association Name="tb_category_tb_product" Member="tb_category" ThisKey="Category_Id" OtherKey="Id" Type="tb_category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_user" Member="tb_users">
    <Type Name="tb_user">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Fullname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiledBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiledDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_productImage" Member="tb_productImages">
    <Type Name="tb_productImage">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Product_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tb_product_tb_productImage" Member="tb_product" ThisKey="Product_Id" OtherKey="Id" Type="tb_product" IsForeignKey="true" />
    </Type>
  </Table>
</Database>